name: hotel_reservation
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=3.3.1 <4.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  flutter_rating_bar: ^4.0.1
  readmore: ^2.2.0
  carousel_slider: ^4.2.1
  intl: ^0.18.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Urbanist
      fonts: 
        - asset: assets/fonts/UrbanistRomanExtraBold.ttf
          weight: 800
        - asset: assets/fonts/UrbanistRomanMedium.ttf
          weight: 500
        - asset: assets/fonts/UrbanistRomanSemiBold.ttf
          weight: 600
        - asset: assets/fonts/UrbanistRomanBold.ttf
          weight: 700
